apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reddit-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-ci"
spec:
  tls:
  - hosts:
    - demo.shubhamk.online
    secretName: tls-cert
  ingressClassName: nginx
  rules:
  - host: demo.shubhamk.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reddit-clone-service
            port:
              number: 3000
