apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  # Secret names are always required.
  secretName: tls-cert
  dnsNames:
  - demo.shubhamk.online
  issuerRef:
    name: letsencrypt-ci
    kind: ClusterIssuer
